-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 02:05:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Rideshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rideshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Rideshare` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `Rideshare` ;

-- -----------------------------------------------------
-- Table `Rideshare`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Person` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Person` (
  `id` CHAR(10) NOT NULL,
  `first_name` TEXT NOT NULL,
  `last_name` TEXT NOT NULL,
  `phone` VARCHAR(32) NOT NULL,
  `email` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Address` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Address` (
  `id` CHAR(10) NOT NULL,
  `line` TEXT NOT NULL,
  `apt` CHAR(10) NULL DEFAULT NULL,
  `city` CHAR(15) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `postalCode` INT(11) NOT NULL,
  `Person` CHAR(10) NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Address_Person_FK` (`Person` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `Address_Person_FK`
    FOREIGN KEY (`Person`)
    REFERENCES `Rideshare`.`Person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Driver` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Driver` (
  `licence_number` CHAR(10) NOT NULL,
  `Person` CHAR(10) NOT NULL,
  `expiration_date` DATE NOT NULL,
  PRIMARY KEY (`licence_number`),
  INDEX `Driver_Person_FK` (`Person` ASC) VISIBLE,
  UNIQUE INDEX `Person_UNIQUE` (`Person` ASC) VISIBLE,
  UNIQUE INDEX `licence_number_UNIQUE` (`licence_number` ASC) VISIBLE,
  CONSTRAINT `Driver_Person_FK`
    FOREIGN KEY (`Person`)
    REFERENCES `Rideshare`.`Person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Van`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Van` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Van` (
  `plate_number` CHAR(10) NOT NULL,
  `fuel` INT(11) NOT NULL,
  `num_of_seat` INT(11) NOT NULL,
  PRIMARY KEY (`plate_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Location` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Location` (
  `id` CHAR(10) NOT NULL,
  `latitude_longitude` TEXT NOT NULL,
  `Van` CHAR(10) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `Location_Van_FK` (`Van` ASC) VISIBLE,
  CONSTRAINT `Location_Van_FK`
    FOREIGN KEY (`Van`)
    REFERENCES `Rideshare`.`Van` (`plate_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Status` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Status` (
  `id` CHAR(10) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Ride`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Ride` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Ride` (
  `id` CHAR(10) NOT NULL,
  `Status` CHAR(10) NOT NULL,
  `Van` CHAR(10) NOT NULL,
  `Driver` CHAR(10) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `Ride_Status_FK` (`Status` ASC) VISIBLE,
  INDEX `Ride_Van_FK` (`Van` ASC) VISIBLE,
  INDEX `Ride_Driver_FK` (`Driver` ASC) VISIBLE,
  CONSTRAINT `Ride_Driver_FK`
    FOREIGN KEY (`Driver`)
    REFERENCES `Rideshare`.`Driver` (`licence_number`),
  CONSTRAINT `Ride_Status_FK`
    FOREIGN KEY (`Status`)
    REFERENCES `Rideshare`.`Status` (`id`),
  CONSTRAINT `Ride_Van_FK`
    FOREIGN KEY (`Van`)
    REFERENCES `Rideshare`.`Van` (`plate_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`User` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`User` (
  `username` CHAR(10) NOT NULL,
  `Person` CHAR(10) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `User_Person_FK` (`Person` ASC) VISIBLE,
  CONSTRAINT `User_Person_FK`
    FOREIGN KEY (`Person`)
    REFERENCES `Rideshare`.`Person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Request` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`Request` (
  `id` CHAR(10) NOT NULL,
  `from_Address` CHAR(10) NOT NULL,
  `to_Address` CHAR(10) NOT NULL,
  `Status` CHAR(10) NOT NULL,
  `num_of_people` INT(11) NOT NULL,
  `User` CHAR(10) NOT NULL,
  `Ride` CHAR(10) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `Request_from_Address_FK` (`from_Address` ASC) VISIBLE,
  INDEX `Request_to_Address_FK` (`to_Address` ASC) VISIBLE,
  INDEX `Request_Status_FK` (`Status` ASC) VISIBLE,
  INDEX `Request_User_FK` (`User` ASC) VISIBLE,
  INDEX `Request_Ride_FK` (`Ride` ASC) VISIBLE,
  CONSTRAINT `Request_Ride_FK`
    FOREIGN KEY (`Ride`)
    REFERENCES `Rideshare`.`Ride` (`id`),
  CONSTRAINT `Request_Status_FK`
    FOREIGN KEY (`Status`)
    REFERENCES `Rideshare`.`Status` (`id`),
  CONSTRAINT `Request_User_FK`
    FOREIGN KEY (`User`)
    REFERENCES `Rideshare`.`User` (`username`),
  CONSTRAINT `Request_from_Address_FK`
    FOREIGN KEY (`from_Address`)
    REFERENCES `Rideshare`.`Address` (`id`),
  CONSTRAINT `Request_to_Address_FK`
    FOREIGN KEY (`to_Address`)
    REFERENCES `Rideshare`.`Address` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Rideshare`.`VanNotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`VanNotes` ;

CREATE TABLE IF NOT EXISTS `Rideshare`.`VanNotes` (
  `id` CHAR(10) NOT NULL,
  `Van` CHAR(10) NOT NULL,
  `Person` CHAR(10) NOT NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `VanNotes_Van_FK` (`Van` ASC) VISIBLE,
  INDEX `VanNotes_Person_FK` (`Person` ASC) VISIBLE,
  CONSTRAINT `VanNotes_Person_FK`
    FOREIGN KEY (`Person`)
    REFERENCES `Rideshare`.`Person` (`id`),
  CONSTRAINT `VanNotes_Van_FK`
    FOREIGN KEY (`Van`)
    REFERENCES `Rideshare`.`Van` (`plate_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `Rideshare` ;

-- -----------------------------------------------------
-- Placeholder table for view `Rideshare`.`Full_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rideshare`.`Full_Address` (`id` INT, `Contact_Address` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Rideshare`.`InProgress_Rides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rideshare`.`InProgress_Rides` (`id` INT, `User` INT, `Driver` INT, `Van` INT, `From` INT, `To` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Rideshare`.`Rider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rideshare`.`Rider` (`username` INT, `first_name` INT, `last_name` INT, `phone` INT, `email` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Rideshare`.`Rider_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rideshare`.`Rider_Address` (`username` INT, `Full Name` INT, `email` INT, `Full_Address` INT, `Address Name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Rideshare`.`Rides_InQueue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rideshare`.`Rides_InQueue` (`id` INT, `User` INT, `From` INT, `To` INT);

-- -----------------------------------------------------
-- View `Rideshare`.`Full_Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Full_Address`;
DROP VIEW IF EXISTS `Rideshare`.`Full_Address` ;
USE `Rideshare`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ubuntu`@`%` SQL SECURITY DEFINER VIEW `Rideshare`.`Full_Address` AS select `F`.`id` AS `id`,if(isnull(`F`.`apt`),concat(`F`.`line`,' ',`F`.`city`,' ',`F`.`state`,' ',`F`.`postalCode`),concat(`F`.`line`,' ',`F`.`apt`,' ',`F`.`city`,' ',`F`.`state`,' ',`F`.`postalCode`)) AS `Contact_Address` from `Rideshare`.`Address` `F`;

-- -----------------------------------------------------
-- View `Rideshare`.`InProgress_Rides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`InProgress_Rides`;
DROP VIEW IF EXISTS `Rideshare`.`InProgress_Rides` ;
USE `Rideshare`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ubuntu`@`%` SQL SECURITY DEFINER VIEW `Rideshare`.`InProgress_Rides` AS select `R`.`id` AS `id`,`Req`.`User` AS `User`,`R`.`Driver` AS `Driver`,`R`.`Van` AS `Van`,`FA`.`Contact_Address` AS `From`,`FA_`.`Contact_Address` AS `To` from (((`Rideshare`.`Request` `Req` join `Rideshare`.`Ride` `R`) join `Rideshare`.`Full_Address` `FA`) join `Rideshare`.`Full_Address` `FA_`) where ((`R`.`Status` = 2) and (`Req`.`Ride` = `R`.`id`) and (`Req`.`from_Address` = `FA`.`id`) and (`Req`.`to_Address` = `FA_`.`id`));

-- -----------------------------------------------------
-- View `Rideshare`.`Rider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Rider`;
DROP VIEW IF EXISTS `Rideshare`.`Rider` ;
USE `Rideshare`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ubuntu`@`%` SQL SECURITY DEFINER VIEW `Rideshare`.`Rider` AS select `U`.`username` AS `username`,`P`.`first_name` AS `first_name`,`P`.`last_name` AS `last_name`,`P`.`phone` AS `phone`,`P`.`email` AS `email` from (`Rideshare`.`User` `U` join `Rideshare`.`Person` `P`) where (`U`.`Person` = `P`.`id`);

-- -----------------------------------------------------
-- View `Rideshare`.`Rider_Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Rider_Address`;
DROP VIEW IF EXISTS `Rideshare`.`Rider_Address` ;
USE `Rideshare`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ubuntu`@`%` SQL SECURITY DEFINER VIEW `Rideshare`.`Rider_Address` AS select `U`.`username` AS `username`,concat(`P`.`first_name`,' ',`P`.`last_name`) AS `Full Name`,`P`.`email` AS `email`,if(isnull(`A`.`apt`),concat(`A`.`line`,' ',`A`.`city`,' ',`A`.`state`,' ',`A`.`postalCode`),concat(`A`.`line`,' ',`A`.`apt`,' ',`A`.`city`,' ',`A`.`state`,' ',`A`.`postalCode`)) AS `Full_Address`,`A`.`name` AS `Address Name` from ((`Rideshare`.`User` `U` join `Rideshare`.`Person` `P`) join `Rideshare`.`Address` `A`) where ((`U`.`Person` = `P`.`id`) and (`P`.`id` = `A`.`Person`) and (`A`.`Person` is not null));

-- -----------------------------------------------------
-- View `Rideshare`.`Rides_InQueue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rideshare`.`Rides_InQueue`;
DROP VIEW IF EXISTS `Rideshare`.`Rides_InQueue` ;
USE `Rideshare`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ubuntu`@`%` SQL SECURITY DEFINER VIEW `Rideshare`.`Rides_InQueue` AS select `Req`.`id` AS `id`,`Req`.`User` AS `User`,`FA`.`Contact_Address` AS `From`,`FA_`.`Contact_Address` AS `To` from ((`Rideshare`.`Request` `Req` join `Rideshare`.`Full_Address` `FA`) join `Rideshare`.`Full_Address` `FA_`) where ((`Req`.`Status` = 2) and (`Req`.`from_Address` = `FA`.`id`) and (`Req`.`to_Address` = `FA_`.`id`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
